# Generated by Django 5.1.5 on 2025-02-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='brand',
            field=models.CharField(blank=True, choices=[('Amouage', 'Amouage'), ('Balmain', 'Balmain'), ('Lalique', 'Lalique'), ('None', 'None'), ('Chopard', 'Chopard')], max_length=15, null=True),
        ),
    ]
