# Generated by Django 5.1.5 on 2025-01-31 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_products_salepers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Shampoo', 'SHAMPOO'), ('Shower Gel', 'SHOWERHEL'), ('Liquid Soap', 'LIQUIDSOAP'), ('Room Sprey', 'ROOMSPREY'), ('Body Lotion', 'BODYLOTION')], max_length=15, null=True),
        ),
    ]
