# Generated by Django 5.1.5 on 2025-01-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.CharField(blank=True, choices=[('Shampoo', 'SHAMPOO'), ('Shower Gel', 'SHOWE RGEL'), ('Liquid Soap', 'LIQUID SOAP'), ('Room Sprey', 'ROOM SPREY'), ('Body Lotion', 'BODY LOTION')], max_length=15, null=True),
        ),
    ]
