# Generated by Django 5.1.5 on 2025-01-25 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_customuser_is_active_customuser_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_staff',
        ),
    ]
