# Generated by Django 5.1.5 on 2025-02-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=100, verbose_name='Total Price'),
        ),
    ]
