# Generated by Django 5.1.5 on 2025-01-26 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_profile_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
