# Generated by Django 5.1.5 on 2025-03-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_remove_orders_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='PaymentMeth',
            field=models.CharField(blank=True, choices=[('PayPal', 'PAYPAL'), ('PayPal Card', 'PAYPAL CARD'), ('Antikatavolh', 'ANTIKATAVOLH')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=100, verbose_name='Total Price'),
        ),
    ]
