# Generated by Django 5.1.5 on 2025-03-16 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='googlelogin',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
