# Generated by Django 5.1.5 on 2025-01-28 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='owner',
        ),
    ]
