# Generated by Django 5.1.5 on 2025-01-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0011_remove_customuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
