# Generated by Django 5.1.5 on 2025-01-28 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0012_alter_customuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='email',
        ),
    ]
